# Gradle performance improvements
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.configureondemand=true

# Kotlin configurations
kotlin.incremental=true
kotlin.caching.enabled=true
kotlin.parallel.tasks.in.project=true

# Build cache directory
org.gradle.daemon.idletimeout=3600000