apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
  labels:
    app: fastfood
data:
  SPRING_PROFILES_ACTIVE: "dev"
  DATABASE_URL: "jdbc:mysql://mysql-svc:3306/fastfood"
  DATABASE_DIALECT: "org.hibernate.dialect.MySQLDialect"
  SERVER_PORT: "8080"
  TZ: "America/Sao_Paulo"
